controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # Declare controller name and type
    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Controller properties and joints to use
effort_controllers:
  ros__parameters:
    joints:
      - joint1
      - joint2
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort