# Controller manager configuration
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    # Declare controller name and type
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

# Controller properties and joints to use
forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position